### ISSUE TITLE
New release 1.8.0 with Shelly support

### ISSUE THREAD

**Issue by cweiske** [Domi04151309/HomeApp#63]
It would be nice if there was an official release on f-droid with shelly support.

Is something missing for a release in your eyes?

----

- [x] #31
- [x] #27
- [x] #64

**Comment by Domi04151309** [comment]
I would like to make the refresh parameter work with direct view before the next release. Other than that, there is nothing missing in my eyes.
Since, from my experience, F-Droid looks for updates on Thursdays, expect a new release around next week.

**Comment by znbrain** [comment]
I have tested the actual branch (shelly+espeasy-real-time-status) with two ESPEasy-Devices.
With one Device i found a Problem. On this there are a lot of Sensors attached, so i must scroll down on the Device-Page. 
At the bottom of the List there are the first three Values again instead of two Temperature-Sensors and one Switch.

Here ist the Json-Output from this device.
[status.json.txt](https://github.com/Domi04151309/HomeApp/files/7817856/status.json.txt)
![Screenshot_20220105-222108_Home](https://user-images.githubusercontent.com/5909446/148291365-324942ca-722b-4c7a-a06b-a2945365cd80.jpg)

**Comment by cweiske** [comment]
v1.8.0 is available on f-droid! https://f-droid.org/en/packages/io.github.domi04151309.home/
