### ISSUE TITLE
[Feature Request] Integration with alarms app

### ISSUE THREAD

**Issue by Biasio** [Domi04151309/HomeApp#74]
*Hi! I was wondering if it is possible to implement the app with some type of macro, in particular with alarms.*

_When the alarm first rings in the morning you can configure the app to turn on a light in your bedroom automatically._

<details>
  <maybe it's difficult to implement macros in general and maybe also interact with alarm apps. It could just work to set an alarm in the app itself><b></summary>

  Thank you for your hard work!

**Comment by Domi04151309** [comment]
I do not think that this is possible. It would require an own custom alarm app that can communicate with this app since there is no easy integration available. However, you can try using [Google Home routines with Google Assistant](https://support.google.com/assistant/answer/7672035?hl=en&co=GENIE.Platform%3DAndroid) in the [Clock app](https://www.howtogeek.com/406742/how-to-set-up-routines-in-google-clock-on-android/) from Google.
